version: '3.7'

services:
  # MySQL
  mysql2:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/my.conf:/etc/mysql/my.conf
    ports:
      - 23306:3306
    restart: always

  # Redis
  redis:
    image: redis:latest
    container_name: ds_redis
    env_file:
      - ./.env
    ports:
      - 26379:6379
    restart: always
